### ISSUE TITLE
Add Code of Conduct.md file

### ISSUE THREAD

**Issue by preronagit** [Abiji-2020/minds-go-sdk#1]
The repository does not contain the code of conduct.md file containing the guidelines for the contributors.

**Comment by preronagit** [comment]
@Abiji-2020   Sir, I want to resolve this issue. Can you please assign it to me under the label of hacktoberfest?

**Comment by Abiji-2020** [comment]
> @Abiji-2020 Sir, I want to resolve this issue. Can you please assign it to me under the label of hacktoberfest?

I have assigned you feel free to open a PR with a updated code.
